import { ethers } from 'ethers';

// GitHub configuration for dynamically sourcing issues as bounties
export const GITHUB_OWNER = 'subodh-thallada';
export const GITHUB_REPO = 'US-Elections-2024';

export const MOCK_BOUNTIES = [
    {
        id: 'mock-1',
        projectId: '1',
        issueId: '2',
        issueNumber: '2',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/2`,
        issueTitle: 'Resolve intermittent memory leak in WebSocket connection pool',
        projectName: 'openmuster-core',
        projectOwner: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
        amount: ethers.utils.parseUnits('400', 18),
        difficultyLevel: 'hard',
        createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    },
    {
        id: 'mock-2',
        projectId: '1',
        issueId: '3',
        issueNumber: '3',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/3`,
        issueTitle: 'Write comprehensive unit and integration tests for auth middleware',
        projectName: 'openmuster-core',
        projectOwner: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
        amount: ethers.utils.parseUnits('250', 18),
        difficultyLevel: 'easy',
        createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    },
    {
        id: 'mock-3',
        projectId: '2',
        issueId: '4',
        issueNumber: '4',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/4`,
        issueTitle: 'Design and implement accessible dark mode with theme persistence',
        projectName: 'shadowbounty-ui',
        projectOwner: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
        amount: ethers.utils.parseUnits('450', 18),
        difficultyLevel: 'hard',
        createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    },
    {
        id: 'mock-4',
        projectId: '2',
        issueId: '5',
        issueNumber: '5',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/5`,
        issueTitle: 'Rewrite blockchain integration for multi-chain support and performance',
        projectName: 'shadowbounty-ui',
        projectOwner: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
        amount: ethers.utils.parseUnits('800', 18),
        difficultyLevel: 'expert',
        createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    },
    {
        id: 'mock-5',
        projectId: '3',
        issueId: '6',
        issueNumber: '6',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/6`,
        issueTitle: 'Update and expand documentation with examples and fix outdated instructions',
        projectName: 'ethereum-smart-contracts',
        projectOwner: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
        amount: ethers.utils.parseUnits('120', 18),
        difficultyLevel: 'medium',
        createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    },
    {
        id: 'mock-6',
        projectId: '3',
        issueId: '7',
        issueNumber: '7',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/7`,
        issueTitle: 'Implement advanced gas optimizations with custom assembly and benchmarks',
        projectName: 'ethereum-smart-contracts',
        projectOwner: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
        amount: ethers.utils.parseUnits('900', 18),
        difficultyLevel: 'expert',
        createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    },
    {
        id: 'mock-7',
        projectId: '4',
        issueId: '8',
        issueNumber: '8',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/8`,
        issueTitle: 'Enhance GitHub OAuth flow with better error recovery and user feedback',
        projectName: 'oauth-server',
        projectOwner: '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
        amount: ethers.utils.parseUnits('300', 18),
        difficultyLevel: 'hard',
        createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    },
    {
        id: 'mock-8',
        projectId: '4',
        issueId: '9',
        issueNumber: '9',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/9`,
        issueTitle: 'Implement robust API rate limit error handling with retry/backoff',
        projectName: 'oauth-server',
        projectOwner: '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
        amount: ethers.utils.parseUnits('220', 18),
        difficultyLevel: 'medium',
        createdAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
    },
    {
        id: 'mock-9',
        projectId: '5',
        issueId: '10',
        issueNumber: '10',
        issueUrl: `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/issues/10`,
        issueTitle: 'Create responsive bounty card with animations and accessibility support',
        projectName: 'contributor-dashboard',
        projectOwner: '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65',
        amount: ethers.utils.parseUnits('200', 18),
        difficultyLevel: 'medium',
        createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    },
];
